### ISSUE TITLE
MarCom checklist for 2/16 campaign launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#123]
Launch checklist for Marketing and Comms activity supporting official campaign launch on 2/17. 
- [x] Op-ed #30 (approved / pitching in process)
- [x] FAQ for press pitch #32 (needs policy team signoff)
- [x] Mark's Campaign blog for blog.mozilla.org and Medium #33 (needs policy team signoff)
- [x] Chapter 1 blog post for Medium #33 (needs policy team signoff)
- [x] Setup Medium publication #120 (update visuals + adding link back to website footer)
- [x] Updated native video asset with branded bumper for social #109
- [x] Create a YouTube channel in order to be able to distribute embed code to media (needs branding)
- [x] Finalize 7 tweets for first 2 weeks of social #52 (needs policy team signoff)
- [x] Finalize 7 FB posts for first 2 weeks of social #52 (needs policy team signoff)
- [x] Paid media campaign #52 (need design/copy/native video + needs policy team signoff)
- [x] Launch Adwords campaign #53 (needs policy review)
- [x] Mozilla.org tile #57 (updated graphics w/ new copy + needs policy review)
- [x] FF&You #69 (final copy and design + needs policy signoff)
- [x] Teach.mozilla.org banner https://github.com/mozilla/teach.mozilla.org/issues/1619 (needs policy signoff)
- [x] MLN community newsletter promo #97 (needs policy signoff)
- [x] Advocacy.mozilla.org banner https://github.com/mozilla/advocacy.mozilla.org/pull/54#issuecomment-182593097 (needs policy signoff)

cc/ @KevZawacki @lovegushwa @natalieworth

**Comment by HPaulJohnson** [comment]
all unchecked items have been submitted for final review by policy.

**Comment by valianttry** [comment]
@HPaulJohnson or @KevZawacki or @shaghdoosti can you drop in the link to the spreadsheet that holds the list of content and approval steps? I can't seem to find it atm.

**Comment by valianttry** [comment]
Everything with a "Y" in column J has full approval to go live:
https://docs.google.com/spreadsheets/d/1MiPaWtpXqYdQ5iUDb3oNemicU5RDguJhVQB6fVlHQEo/edit#gid=0

Anything we can't change that's already launched (e.g. it would need to be redesigned, re-approved, and cause pain) does not need to conform to the latest approved language. (That could change if something is noticed and there is grumbling, but for now let's not poke the bear.)
