### ISSUE TITLE
MarCom checklist for Beat 2 Launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#170]
Launch checklist for Marketing and Comms activity supporting launch of beat 2 content on 2/24.
- [x] Mark's blog for blog.mozilla.org and Medium #34 (needs policy team signoff)
- [ ] Simon's encryption explainer blog for Medium #34 (complete draft + policy team signoff)
- [x] Wave 2 of media pitching #32 (pitch needs policy team signoff)
- [ ] 10 Facts about encryption for media packet #32 (needs policy team signoff)
- [x] Get signed SOW for Just Media to begin paid media promotion (bug being worked)
- [x] Finalize 5 tweets for video 2 promotion #138 (submitted for policy signoff)
- [x] Finalize 5 FB posts for video 2 promotion #138 (submitted for policy signoff)
- [x] Send updated social assets and video 2 to Just Media for testing in paid channels #138
- [x] Update share messaging on microsite #179 
- [x] Upload chapter 2 video to YouTube channel 
- [ ] Begin tests of landing page versions via Optimizely #132 (need to regain access to Optimizely accounts)
- [ ] Begin tests of social share messages via Share Progress #24 (awaiting ETA from Share Progress)

cc/ @KevZawacki

**Comment by adamlofting** [comment]
We have access to Optimizely again.

**Comment by HPaulJohnson** [comment]
Optimizely, Share Progress, and outstanding blog pieces moving to beat 3.
