### ISSUE TITLE
MarCom Checklist for Beat 4 Launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#193]
Launch checklist for Marketing and Comms activity supporting launch of beat 4 content on 3/9.
- [x] Add video 3 and descriptions to landing page #198 
- [x] Mark's blog for blog.mozilla.org and Medium #36  (needs MS signoff)
- [x] Beat 4 media pitching
- [x] 10 Facts about privacy/encryption for media packet and medium post #32
- [x] Finalize basic FB/Twitter posts for video 3 promotion #144 
- [x] Update basic share messages on landing page for beat 4 #196 
- [x] Implement new Share Progress on microsite #191 
- [x] Finalize messaging for Share Progress A/B testing #194 
- [x] Upload video 3 to YouTube channel 
- [x] Review Just Media results for Paid Campaign and optimize for Beat 4
- [x] Finalize other Phase 3 social assets #144 (in design phase)
- [x] Evaluate possible landing page tests via Optimizely to maximize sharing in March #195 

cc/ @KevZawacki

**Comment by KevZawacki** [comment]
- [x] [beat 4 pitch](https://docs.google.com/document/d/1m00wjQZKtoW1c4IJHKz2fZfkm_pQ6nBYhiteDWd3OhY/edit)

**Comment by HPaulJohnson** [comment]
Any open items rolling over to beat 5 checklist: #221
