### ISSUE TITLE
MarCom Checklist for Beat 5 Launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#221]
Launch checklist for Marketing and Comms activity supporting launch of beat 5 content on 3/23.
- [x] Update landing page with video 4 + pledge
- [x] Add video 4 and descriptions to evergreen page for use in social and other non-email channels
- [x] Mark's blog for blog.mozilla.org and Medium #37 
- [x] Beat 5 media pitching #32 
- [x] Finalize basic FB/Twitter posts for video 4 promotion #212
- [x] Implement Share Progress test(s) for post-pledge #233 
- [x] Update default share language on microsite #234 
- [x] Upload video 4 to YouTube channel
